// Auto-generated file - do not edit manually
// Generated at build time from MDX files
import type { Post } from "@/types";

export const postsCache: Post[] = [
  {
    "id": "resim",
    "path": "resim",
    "date": "January 3, 2026",
    "title": "İnternetten Silemediğim O Resim",
    "minuteToRead": 2,
    "language": "tr-TR",
    "category": [
      "Personal"
    ],
    "link": "https://cihat.dev/2026/resim",
    "description": "İnternetten silemediğim o resim",
    "issueNumber": 17,
    "views": 0,
    "viewsFormatted": "0"
  },
  {
    "id": "boulder",
    "path": "boulder",
    "date": "November 16, 2025",
    "title": "Boulder",
    "minuteToRead": 5,
    "language": "tr-TR",
    "category": [
      "Sport",
      "Bouldering"
    ],
    "link": "https://cihat.dev/2025/boulder",
    "description": "Boulder",
    "issueNumber": 15,
    "views": 0,
    "viewsFormatted": "0"
  },
  {
    "id": "vibe-coding",
    "path": "vibe-coding",
    "date": "November 16, 2025",
    "title": "Vibe Coding",
    "minuteToRead": 5,
    "language": "tr-TR",
    "category": [
      "Vibe Coding"
    ],
    "link": "https://cihat.dev/2025/vibe-coding",
    "description": "About Vibe Coding",
    "issueNumber": 16,
    "views": 0,
    "viewsFormatted": "0"
  },
  {
    "id": "system-design",
    "path": "system-design",
    "date": "August 22, 2025",
    "title": "System Design (New Journey)",
    "minuteToRead": 30,
    "language": "en-US",
    "category": "Technical",
    "link": "https://cihat.dev/2025/system-design",
    "description": "System Design",
    "issueNumber": 14,
    "views": 0,
    "viewsFormatted": "0"
  },
  {
    "id": "music",
    "path": "music",
    "date": "April 1, 2025",
    "title": "Music",
    "minuteToRead": 2,
    "language": "en-US",
    "category": [
      "Entertainment",
      "Music"
    ],
    "link": "https://cihat.dev/2025/music",
    "description": "some artists/music I listen to often",
    "issueNumber": 13,
    "views": 0,
    "viewsFormatted": "0"
  },
  {
    "id": "askerlik",
    "path": "askerlik",
    "date": "March 31, 2025",
    "title": "Askerlik",
    "minuteToRead": 2,
    "language": "tr-TR",
    "category": [
      "Personal",
      "Askerlik"
    ],
    "link": "https://cihat.dev/2025/askerlik",
    "description": "05 Nisan 2025 gunu baslayan askerlik uzerine",
    "issueNumber": 12,
    "views": 0,
    "viewsFormatted": "0"
  },
  {
    "id": "system-design-acid-properties",
    "path": "system-design/acid-properties",
    "date": "January 1, 2025",
    "title": "ACID Properties - System Design",
    "minuteToRead": 5,
    "language": "en-US",
    "category": "Etc",
    "link": "https://cihat.dev/2025/system-design/acid-properties",
    "description": "Understanding ACID properties in database transactions: Atomicity, Consistency, Isolation, and Durability",
    "issueNumber": 0,
    "views": 0,
    "viewsFormatted": "0"
  },
  {
    "id": "system-design-caching-strategies",
    "path": "system-design/caching-strategies",
    "date": "January 1, 2025",
    "title": "Caching Strategies - System Design",
    "minuteToRead": 5,
    "language": "en-US",
    "category": "Etc",
    "link": "https://cihat.dev/2025/system-design/caching-strategies",
    "description": "Understanding different caching strategies and patterns for improving application performance",
    "issueNumber": 0,
    "views": 0,
    "viewsFormatted": "0"
  },
  {
    "id": "system-design-cap-teorem",
    "path": "system-design/cap-teorem",
    "date": "January 1, 2025",
    "title": "CAP Teoremi",
    "minuteToRead": 5,
    "language": "en-US",
    "category": "Etc",
    "link": "https://cihat.dev/2025/system-design/cap-teorem",
    "description": "CAP Teoremi",
    "issueNumber": 0,
    "views": 0,
    "viewsFormatted": "0"
  },
  {
    "id": "system-design-cdn",
    "path": "system-design/cdn",
    "date": "January 1, 2025",
    "title": "CDN (Content Delivery Networks) - System Design",
    "minuteToRead": 5,
    "language": "en-US",
    "category": "Etc",
    "link": "https://cihat.dev/2025/system-design/cdn",
    "description": "Understanding Content Delivery Networks and their role in improving website performance and global content distribution",
    "issueNumber": 0,
    "views": 0,
    "viewsFormatted": "0"
  },
  {
    "id": "system-design-challenges",
    "path": "system-design/challenges",
    "date": "January 1, 2025",
    "title": "Practical Challenges & Exercises - System Design",
    "minuteToRead": 5,
    "language": "en-US",
    "category": "Etc",
    "link": "https://cihat.dev/2025/system-design/challenges",
    "description": "Hands-on projects to reinforce system design concepts and build real-world skills",
    "issueNumber": 0,
    "views": 0,
    "viewsFormatted": "0"
  },
  {
    "id": "system-design-circuit-breaker",
    "path": "system-design/circuit-breaker",
    "date": "January 1, 2025",
    "title": "Circuit Breaker Pattern - System Design",
    "minuteToRead": 5,
    "language": "en-US",
    "category": "Etc",
    "link": "https://cihat.dev/2025/system-design/circuit-breaker",
    "description": "Understanding the Circuit Breaker pattern for fault tolerance and resilience in distributed systems",
    "issueNumber": 0,
    "views": 0,
    "viewsFormatted": "0"
  },
  {
    "id": "system-design-database-design-patterns",
    "path": "system-design/database-design-patterns",
    "date": "January 1, 2025",
    "title": "Database Design Patterns - System Design",
    "minuteToRead": 5,
    "language": "en-US",
    "category": "Etc",
    "link": "https://cihat.dev/2025/system-design/database-design-patterns",
    "description": "Understanding database design patterns for scalable and efficient data storage",
    "issueNumber": 0,
    "views": 0,
    "viewsFormatted": "0"
  },
  {
    "id": "system-design-load-balancing",
    "path": "system-design/load-balancing",
    "date": "January 1, 2025",
    "title": "Load Balancing - System Design",
    "minuteToRead": 5,
    "language": "en-US",
    "category": "Etc",
    "link": "https://cihat.dev/2025/system-design/load-balancing",
    "description": "Understanding load balancing strategies and algorithms for distributing traffic across multiple servers",
    "issueNumber": 0,
    "views": 0,
    "viewsFormatted": "0"
  },
  {
    "id": "system-design-message-queues",
    "path": "system-design/message-queues",
    "date": "January 1, 2025",
    "title": "Message Queues - System Design",
    "minuteToRead": 5,
    "language": "en-US",
    "category": "Etc",
    "link": "https://cihat.dev/2025/system-design/message-queues",
    "description": "Understanding message queues and messaging patterns for building reliable distributed systems",
    "issueNumber": 0,
    "views": 0,
    "viewsFormatted": "0"
  },
  {
    "id": "system-design-microservices",
    "path": "system-design/microservices",
    "date": "January 1, 2025",
    "title": "Microservices Architecture - System Design",
    "minuteToRead": 5,
    "language": "en-US",
    "category": "Etc",
    "link": "https://cihat.dev/2025/system-design/microservices",
    "description": "Understanding microservices architecture patterns and best practices for building scalable distributed systems",
    "issueNumber": 0,
    "views": 0,
    "viewsFormatted": "0"
  },
  {
    "id": "system-design-rate-limiting",
    "path": "system-design/rate-limiting",
    "date": "January 1, 2025",
    "title": "Rate Limiting - System Design",
    "minuteToRead": 5,
    "language": "en-US",
    "category": "Etc",
    "link": "https://cihat.dev/2025/system-design/rate-limiting",
    "description": "Understanding rate limiting algorithms and strategies for protecting APIs and managing system resources",
    "issueNumber": 0,
    "views": 0,
    "viewsFormatted": "0"
  },
  {
    "id": "system-design-roadmap",
    "path": "system-design/roadmap",
    "date": "January 1, 2025",
    "title": "System Design Roadmap 2025 - Learning Path",
    "minuteToRead": 5,
    "language": "en-US",
    "category": "Etc",
    "link": "https://cihat.dev/2025/system-design/roadmap",
    "description": "A structured learning path for mastering system design in 2025, designed for beginners to advanced practitioners",
    "issueNumber": 0,
    "views": 0,
    "viewsFormatted": "0"
  },
  {
    "id": "system-design-technology-stack-2025",
    "path": "system-design/technology-stack-2025",
    "date": "January 1, 2025",
    "title": "System Design Technology Stack 2025 - Essential Tools & Technologies",
    "minuteToRead": 5,
    "language": "en-US",
    "category": "Etc",
    "link": "https://cihat.dev/2025/system-design/technology-stack-2025",
    "description": "Comprehensive guide to the most used technologies, tools, programming languages, and resources for system design in 2025",
    "issueNumber": 0,
    "views": 0,
    "viewsFormatted": "0"
  },
  {
    "id": "oylesine",
    "path": "oylesine",
    "date": "August 20, 2024",
    "title": "Öylesine",
    "minuteToRead": 6,
    "language": "tr-TR",
    "category": [
      "Personal"
    ],
    "link": "https://cihat.dev/2024/oylesine",
    "description": "Oylesine bir şeyler",
    "issueNumber": 11,
    "views": 0,
    "viewsFormatted": "0"
  },
  {
    "id": "agirlik-antrenmanlarina-baslangic",
    "path": "sport/agirlik-antrenmanlarina-baslangic",
    "date": "July 21, 2024",
    "title": "Ağırlık Antrenmanlarına Başlangıç",
    "minuteToRead": 5,
    "language": "tr-TR",
    "category": "Sport",
    "link": "https://cihat.dev/2024/sport/agirlik-antrenmanlarina-baslangic",
    "description": "11 hafta boyunca ağırlık antrenmanlarından neler öğrendim ve neler deneyimledim?",
    "issueNumber": 10,
    "views": 0,
    "viewsFormatted": "0"
  },
  {
    "id": "cs-basics-series",
    "path": "cs-basics-series",
    "date": "February 04, 2024",
    "title": "learn cs basics series #0",
    "minuteToRead": 5,
    "language": "en-US",
    "category": [
      "Learning",
      "Computer Science",
      "Programming"
    ],
    "link": "https://cihat.dev/2024/cs-basics-series",
    "description": "i decided to start this series to overcome my deficiencies in cs.",
    "issueNumber": 9,
    "views": 0,
    "viewsFormatted": "0"
  },
  {
    "id": "cs-basics-series-1-introduction",
    "path": "cs-basics-series/1-introduction",
    "date": "January 1, 2024",
    "title": "Learn CS Basics Series #1",
    "minuteToRead": 5,
    "language": "en-US",
    "category": "Etc",
    "link": "https://cihat.dev/2024/cs-basics-series/1-introduction",
    "description": "#1: Introduction of Cracking The Coding Interview Book",
    "issueNumber": 0,
    "views": 0,
    "viewsFormatted": "0"
  },
  {
    "id": "cs-basics-series-2-data-structures",
    "path": "cs-basics-series/2-data-structures",
    "date": "January 1, 2024",
    "title": "Learn CS Basics Series #2",
    "minuteToRead": 5,
    "language": "en-US",
    "category": "Etc",
    "link": "https://cihat.dev/2024/cs-basics-series/2-data-structures",
    "description": "#2: Data Structures",
    "issueNumber": 0,
    "views": 0,
    "viewsFormatted": "0"
  },
  {
    "id": "cs-basics-series-3-concepts-and-algorithms",
    "path": "cs-basics-series/3-concepts-and-algorithms",
    "date": "January 1, 2024",
    "title": "Learn CS Basics Series #3",
    "minuteToRead": 5,
    "language": "en-US",
    "category": "Etc",
    "link": "https://cihat.dev/2024/cs-basics-series/3-concepts-and-algorithms",
    "description": "#3: Concepts of Algorithms",
    "issueNumber": 0,
    "views": 0,
    "viewsFormatted": "0"
  },
  {
    "id": "cs-basics-series-4-knowledge-based",
    "path": "cs-basics-series/4-knowledge-based",
    "date": "January 1, 2024",
    "title": "Learn CS Basics Series #4",
    "minuteToRead": 5,
    "language": "en-US",
    "category": "Etc",
    "link": "https://cihat.dev/2024/cs-basics-series/4-knowledge-based",
    "description": "#4: Knowledge Based",
    "issueNumber": 0,
    "views": 0,
    "viewsFormatted": "0"
  },
  {
    "id": "uretkenlik-uzerine",
    "path": "uretkenlik-uzerine",
    "date": "August 20, 2023",
    "title": "Üretkenlik Üzerine",
    "minuteToRead": 6,
    "language": "tr-TR",
    "category": [
      "Productivity"
    ],
    "link": "https://cihat.dev/2023/uretkenlik-uzerine",
    "description": "Üretkenlik hakkında okuduğum kitap, düşüncelerimi ve yaptıklarımı paylaşıyorum.",
    "issueNumber": 8,
    "views": 0,
    "viewsFormatted": "0"
  },
  {
    "id": "stoik-felsefe",
    "path": "stoik-felsefe",
    "date": "August 3, 2023",
    "title": "Stoik Felsefeyle Tanışma",
    "minuteToRead": 5,
    "language": "tr-TR",
    "category": "Philosophy",
    "link": "https://cihat.dev/2023/stoik-felsefe",
    "description": "Şu sıralar yeni okumaya, arastirmaya basladigim buyuk ilgi duydugum felsefe olan Stoik Felse hakkinda simdiye kadar ogrendigim konulari okudugum kitaplardan bahsedecegim.",
    "issueNumber": 4,
    "views": 0,
    "viewsFormatted": "0"
  },
  {
    "id": "pro-js-design-patterns",
    "path": "pro-js-design-patterns",
    "date": "July 27, 2023",
    "title": "My Notes from Pro JavaScript Design Patterns",
    "minuteToRead": 5,
    "language": "en-US",
    "category": "Learning",
    "link": "https://cihat.dev/2023/pro-js-design-patterns",
    "description": "My Notes from Pro JavaScript Design Patterns by Ross Harmes and Dustin Diaz",
    "issueNumber": 3,
    "views": 0,
    "viewsFormatted": "0"
  },
  {
    "id": "atomik-aliskanliklar",
    "path": "atomik-aliskanliklar",
    "date": "July 26, 2023",
    "title": "Atomik Alışkanlıklar Kitabindan Notlar",
    "minuteToRead": 5,
    "language": "tr-TR",
    "category": "Productivity",
    "link": "https://cihat.dev/2023/atomik-aliskanliklar",
    "description": "James Clear",
    "issueNumber": 7,
    "views": 0,
    "viewsFormatted": "0"
  },
  {
    "id": "ilk-blog-yazisi",
    "path": "ilk-blog-yazisi",
    "date": "July 16, 2023",
    "title": "Ilk Blog Yazısı",
    "minuteToRead": 3,
    "language": "tr-TR",
    "category": [
      "Personal"
    ],
    "link": "https://cihat.dev/2023/ilk-blog-yazisi",
    "description": "Ilk blog yazimda kendimden ve blogumda yapmayi dusundugum seylerden bahsettim.",
    "issueNumber": 6,
    "views": 0,
    "viewsFormatted": "0"
  },
  {
    "id": "initial-blog-post",
    "path": "initial-blog-post",
    "date": "July 16, 2023",
    "title": "Initial Blog Post",
    "minuteToRead": 3,
    "language": "en-US",
    "category": [
      "Personal"
    ],
    "link": "https://cihat.dev/2023/initial-blog-post",
    "description": "Hello, in this first post, I briefly talked about my plans for implementing and working towards my goals, as well as introduced myself.",
    "issueNumber": 2,
    "views": 0,
    "viewsFormatted": "0"
  },
  {
    "id": "kariyerimde-mentorlugun-onemi",
    "path": "kariyerimde-mentorlugun-onemi",
    "date": "March 9, 2021",
    "title": "Kariyerimde Mentörlüğün Önemi",
    "minuteToRead": 6,
    "language": "tr-TR",
    "category": [
      "Career",
      "Mentorship",
      "Personal"
    ],
    "link": "https://cihat.dev/2021/kariyerimde-mentorlugun-onemi",
    "description": "Kariyerimde mentorluk önemli bir yere sahip. Bu yazıda mentorluk kavramını ve kariyerimdeki önemini anlatıyorum.",
    "issueNumber": 5,
    "views": 0,
    "viewsFormatted": "0"
  }
];
